// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()  // Updated from jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        // Replaced Bintray plugin with maven-publish plugin
        classpath 'com.android.tools.build:gradle:3.6.4'  // You can upgrade to a newer version
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'  // Use a more recent version
    }
}

allprojects {
    repositories {
        mavenCentral()  // Updated from jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}