apply plugin: 'com.android.library'
apply plugin: 'maven-publish'  // Adding the maven-publish plugin

ext {
    bintrayRepo = 'maven'  // This is still used but we will replace it with mavenCentral
    bintrayName = 'crystalrangeseekbar'

    // Maven metadata
    publishedGroupId = 'com.crystal'
    libraryName = 'CrystalRangeSeekbar'
    artifact = 'crystalrangeseekbar'

    libraryDescription = 'An extended version of android range seekbar.'

    gitUrl = 'https://github.com/syedowaisali/crystal-range-seekbar.git'

    libraryVersion = '1.1.4'

    developerId = 'syedowaisali'
    developerName = 'Syed Owais Ali'
    developerEmail = 'dp.owaisali@gmail.com'

    licenseName = 'The Apache Software License, Version 2.0'
    licenseUrl = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
    allLicenses = ["Apache-2.0"]
}

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.0.2'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = publishedGroupId
            artifactId = artifact
            version = libraryVersion

            from components.release  // Use the release component for publication

            pom {
                name = libraryName
                description = libraryDescription
                url = gitUrl

                licenses {
                    license {
                        name = licenseName
                        url = licenseUrl
                    }
                }

                developers {
                    developer {
                        id = developerId
                        name = developerName
                        email = developerEmail
                    }
                }

                scm {
                    connection = "scm:git:$gitUrl"
                    developerConnection = "scm:git:$gitUrl"
                    url = gitUrl
                }
            }
        }
    }

    repositories {
        maven {
            name = 'MavenCentral'
            url = uri("https://repo.maven.apache.org/maven2")
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
